/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    SentimentAnalyzer: typeof import('./src/components/SentimentAnalyzer.vue')['default']
    SentimentResult: typeof import('./src/components/SentimentResult.vue')['default']
    TextInput: typeof import('./src/components/TextInput.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
  }
}
